site_name: "My Digital Portfolio"
theme:
  name: dracula

nav:
  - Home: index.md
  - About me: about.md
  - Classes:
      - AP Networking:
          - Component Cards: classes/ap-networking/202509component-cards.md
          - Command Line Interface: classes/ap-networking/202509CLI.md
          - Determining Security Controls for Devices: classes/ap-networking/202509SecurityControls.md
          - Implementing Security for Devices: classes/ap-networking/202510ImplementSecurity.md
          - Data Movement and Types of Networks: classes/ap-networking/202511Data.md
          - Types of Networks & Connections and Devices: classes/ap-networking/202511TypesNetwork.md

          



