site_name: "My Digital Portfolio"
theme:
  name: dracula

nav:
  - Home: index.md
  - About me: about.md
  - Classes:
      - AP Networking:
          - Component Cards: classes/ap-networking/202509component-cards.md
          - Command Line Interface: classes/ap-networking/202509CLI.md



